In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/drive/MyDrive/Datasets/IMDB Dataset.csv')

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

/tmp/ipykernel_1991/4240984564.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)
/tmp/ipykernel_1991/4240984564.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [5]:
df

                                                  review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production. <br /><br />The...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically there's a family where a little boy ...          0
4      Petter Mattei's "Love in the Time of Money" is...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  I'm going to have to disagree with the previou...          0
49999  No one expects the Star Trek movies to be high...          0

[50000 rows x 2 columns]

In [6]:
import re

In [7]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [8]:
df['review']=df['review'].apply(clean_html)

In [9]:
df.shape

(50000, 2)

In [10]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [11]:
df['review']=df['review'].apply(convert_lower)

In [12]:
df

                                                  review  sentiment
0      one of the other reviewers has mentioned that ...          1
1      a wonderful little production. the filming tec...          1
2      i thought this was a wonderful way to spend ti...          1
3      basically there's a family where a little boy ...          0
4      petter mattei's "love in the time of money" is...          1
...                                                  ...        ...
49995  i thought this movie did a down right good job...          1
49996  bad plot, bad dialogue, bad acting, idiotic di...          0
49997  i am a catholic taught in parochial elementary...          0
49998  i'm going to have to disagree with the previou...          0
49999  no one expects the star trek movies to be high...          0

[50000 rows x 2 columns]

In [13]:
# function to remove special characters

def remove_special(text):
    x=''

    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [14]:
df['review']=df['review'].apply(remove_special)

In [15]:
df

                                                  review  sentiment
0      one of the other reviewers has mentioned that ...          1
1      a wonderful little production  the filming tec...          1
2      i thought this was a wonderful way to spend ti...          1
3      basically there s a family where a little boy ...          0
4      petter mattei s  love in the time of money  is...          1
...                                                  ...        ...
49995  i thought this movie did a down right good job...          1
49996  bad plot  bad dialogue  bad acting  idiotic di...          0
49997  i am a catholic taught in parochial elementary...          0
49998  i m going to have to disagree with the previou...          0
49999  no one expects the star trek movies to be high...          0

[50000 rows x 2 columns]

In [16]:
# Remove the stop words
import nltk

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [18]:
from nltk.corpus import stopwords

In [19]:
stop_words = set(stopwords.words('english'))

In [20]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [21]:
important_words = {
    'no',
    'nor',
    'not',

    'don',
    "don't",

    'didn',
    "didn't",

    'doesn',
    "doesn't",

    'hadn',
    "hadn't",

    'hasn',
    "hasn't",

    'haven',
    "haven't",

    'isn',
    "isn't",

    'aren',
    "aren't",

    'wasn',
    "wasn't",

    'weren',
    "weren't",

    'won',
    "won't",

    'wouldn',
    "wouldn't",

    'couldn',
    "couldn't",

    'shouldn',
    "shouldn't",

    'mustn',
    "mustn't",

    'needn',
    "needn't",

    'mightn',
    "mightn't",

    'shan',
    "shan't",

    'against',

    'but',

    'very',

    'too'
}

In [22]:
for word in important_words:
    stop_words.discard(word)

In [23]:
def remove_stopwords(text):
    x = []

    for i in text.split():
        if i not in stop_words:
            x.append(i)

    return x

In [24]:
df['review'] = df['review'].apply(remove_stopwords)

In [25]:
df

                                                  review  sentiment
0      [one, reviewers, mentioned, watching, 1, oz, e...          1
1      [wonderful, little, production, filming, techn...          1
2      [thought, wonderful, way, spend, time, too, ho...          1
3      [basically, family, little, boy, jake, thinks,...          0
4      [petter, mattei, love, time, money, visually, ...          1
...                                                  ...        ...
49995  [thought, movie, right, good, job, wasn, creat...          1
49996  [bad, plot, bad, dialogue, bad, acting, idioti...          0
49997  [catholic, taught, parochial, elementary, scho...          0
49998  [going, disagree, previous, comment, side, mal...          0
49999  [no, one, expects, star, trek, movies, high, a...          0

[50000 rows x 2 columns]

In [26]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [27]:
def stem_words(text):
    return [ps.stem(word) for word in text]

In [28]:
df['review'] = df['review'].apply(stem_words)

In [29]:
df

                                                  review  sentiment
0      [one, review, mention, watch, 1, oz, episod, h...          1
1      [wonder, littl, product, film, techniqu, veri,...          1
2      [thought, wonder, way, spend, time, too, hot, ...          1
3      [basic, famili, littl, boy, jake, think, zombi...          0
4      [petter, mattei, love, time, money, visual, st...          1
...                                                  ...        ...
49995  [thought, movi, right, good, job, wasn, creati...          1
49996  [bad, plot, bad, dialogu, bad, act, idiot, dir...          0
49997  [cathol, taught, parochi, elementari, school, ...          0
49998  [go, disagre, previou, comment, side, maltin, ...          0
49999  [no, one, expect, star, trek, movi, high, art,...          0

[50000 rows x 2 columns]

In [30]:
# Join back

def join_back(list_input):
    return " ".join(list_input)

In [31]:
df['review']=df['review'].apply(join_back)

In [32]:
df

                                                  review  sentiment
0      one review mention watch 1 oz episod hook righ...          1
1      wonder littl product film techniqu veri unassu...          1
2      thought wonder way spend time too hot summer w...          1
3      basic famili littl boy jake think zombi closet...          0
4      petter mattei love time money visual stun film...          1
...                                                  ...        ...
49995  thought movi right good job wasn creativ origi...          1
49996  bad plot bad dialogu bad act idiot direct anno...          0
49997  cathol taught parochi elementari school nun ta...          0
49998  go disagre previou comment side maltin one sec...          0
49999  no one expect star trek movi high art but fan ...          0

[50000 rows x 2 columns]

In [33]:
X=df.iloc[:,0:1].values

In [34]:
X.shape

(50000, 1)

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(
    max_features=2000,
    ngram_range=(1,2)
)

In [36]:
X=cv.fit_transform(df['review']).toarray()

In [37]:
X.shape

(50000, 2000)

In [38]:
y=df.iloc[:,-1].values

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=2)

In [40]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [41]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [42]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [43]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score

In [45]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.8007
Multinomial 0.8443
Bernaulli 0.8487

In [46]:
import pickle

In [49]:
pickle.dump(clf3, open('model.pkl', 'wb'))

In [50]:
pickle.dump(cv, open('cv.pkl', 'wb'))